services:
  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    expose:
      - "8080"
    image : go-example-api
    environment:
      - DBUSER=firman
      - DBPASS=admin
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config/loki.yaml:/etc/loki/local-config.yaml
  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      # - /var/log:/var/log
      - ./config/promtail.yaml:/etc/promtail/config.yml
      - ./logs/:/var/log/ 
    command: -config.file=/etc/promtail/config.yml
  log-generator:
    image: mingrammer/flog
    command: 
      - --loop
      - --format=json
      - --number=20
      - --delay=100ms
      - --output=/var/log/generated-logs.log
      - --overwrite
      - --type=log
    volumes:
      - ./logs/:/var/log/ 
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
  prometheus:
    image: quay.io/prometheus/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      # - '-storage.local.path=/prometheus'
    ports:
      - 9090:9090
  mysqld-exporter:
    image: quay.io/prometheus/mysqld-exporter
    command:
     - --collect.info_schema.tablestats
     - --mysqld.username=firman:admin
     - --mysqld.address=db:3306
    container_name: mysqld-exporter
    # environment:
    #   - DATA_SOURCE_NAME=firman:admin@(db:3306)/
    ports:
      - 9104:9104
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0
    restart: always
    container_name: godockerDB
    environment:
      MYSQL_DATABASE: 'company'
      MYSQL_USER: 'firman'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD || exit 1"]
      interval: 10s
      retries: 5
      start_period: 30s
volumes:
  grafana-storage:
  my-db: 
  prometheus_data: