services:
  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    expose:
      - "8080"
    image : go-example-api
    environment:
      - DBUSER=firman
      - DBPASS=admin
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
  db:
    image: mysql:8.0
    restart: always
    container_name: godockerDB
    environment:
      MYSQL_DATABASE: 'company'
      MYSQL_USER: 'firman'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD || exit 1"]
      interval: 10s
      retries: 5
      start_period: 30s
volumes:
  grafana-storage:
  my-db: 