{
 "title": "Go Example Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Rate of Internal Server Error In the Last 5 Minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate({job=\"varlogs\"} |= `\"status\":500` [1m])"
    }
   ]
  },
  {
   "title": "Request by methods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method) (rate({job=\"varlogs\"} | json | method != `` [5m]))"
    }
   ]
  },
  {
   "title": "Database Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_up{instance=\"mysqld-exporter:9104\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Max Connection",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_max_connections{instance=\"mysqld-exporter:9104\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_uptime{instance=\"mysqld-exporter:9104\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}